/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fastken_fcfs_FCFSPosixAPI */

#ifndef _Included_com_fastken_fcfs_FCFSPosixAPI
#define _Included_com_fastken_fcfs_FCFSPosixAPI

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fastken_fcfs_FCFSPosixAPI
 * Method:    doInit
 * Signature: ()V
JNIEXPORT void JNICALL Java_com_fastken_fcfs_FCFSPosixAPI_doInit
  (JNIEnv *, jclass);
 */

/*
 * Class:     com_fastken_fcfs_FCFSPosixAPI
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_fastken_fcfs_FCFSPosixAPI_init
  (JNIEnv *env, jobject obj, jstring poolname, jstring filename);

/*
 * Class:     com_fastken_fcfs_FCFSPosixAPI
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fastken_fcfs_FCFSPosixAPI_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
