/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fastken_fcfs_FCFSFile */

#ifndef _Included_com_fastken_fcfs_FCFSFile
#define _Included_com_fastken_fcfs_FCFSFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fastken_fcfs_FCFSFile
 * Method:    doInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fastken_fcfs_FCFSFile_doInit
  (JNIEnv *, jclass);

/*
 * Class:     com_fastken_fcfs_FCFSFile
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fastken_fcfs_FCFSFile_close
  (JNIEnv *, jobject);

/*
 * Class:     com_fastken_fcfs_FCFSFile
 * Method:    sync
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fastken_fcfs_FCFSFile_sync
  (JNIEnv *, jobject);

/*
 * Class:     com_fastken_fcfs_FCFSFile
 * Method:    datasync
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fastken_fcfs_FCFSFile_datasync
  (JNIEnv *, jobject);

/*
 * Class:     com_fastken_fcfs_FCFSFile
 * Method:    write
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_fastken_fcfs_FCFSFile_write
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_fastken_fcfs_FCFSFile
 * Method:    read
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_com_fastken_fcfs_FCFSFile_read
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_fastken_fcfs_FCFSFile
 * Method:    lseek
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_fastken_fcfs_FCFSFile_lseek
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_fastken_fcfs_FCFSFile
 * Method:    allocate
 * Signature: (IJJ)V
 */
JNIEXPORT void JNICALL Java_com_fastken_fcfs_FCFSFile_allocate
  (JNIEnv *, jobject, jint, jlong, jlong);

/*
 * Class:     com_fastken_fcfs_FCFSFile
 * Method:    truncate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_fastken_fcfs_FCFSFile_truncate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_fastken_fcfs_FCFSFile
 * Method:    stat
 * Signature: ()Lcom/fastken/fcfs/FCFSFileStat;
 */
JNIEXPORT jobject JNICALL Java_com_fastken_fcfs_FCFSFile_stat
  (JNIEnv *, jobject);

/*
 * Class:     com_fastken_fcfs_FCFSFile
 * Method:    lock
 * Signature: (JJZZ)V
 */
JNIEXPORT void JNICALL Java_com_fastken_fcfs_FCFSFile_lock
  (JNIEnv *, jobject, jlong, jlong, jboolean, jboolean);

/*
 * Class:     com_fastken_fcfs_FCFSFile
 * Method:    unlock
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_fastken_fcfs_FCFSFile_unlock
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_fastken_fcfs_FCFSFile
 * Method:    utimes
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_com_fastken_fcfs_FCFSFile_utimes
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     com_fastken_fcfs_FCFSFile
 * Method:    chown
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_fastken_fcfs_FCFSFile_chown
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_fastken_fcfs_FCFSFile
 * Method:    chmod
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_fastken_fcfs_FCFSFile_chmod
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_fastken_fcfs_FCFSFile
 * Method:    setxattr
 * Signature: (Ljava/lang/String;[BIII)V
 */
JNIEXPORT void JNICALL Java_com_fastken_fcfs_FCFSFile_setxattr
  (JNIEnv *, jobject, jstring, jbyteArray, jint, jint, jint);

/*
 * Class:     com_fastken_fcfs_FCFSFile
 * Method:    removexattr
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_fastken_fcfs_FCFSFile_removexattr
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_fastken_fcfs_FCFSFile
 * Method:    getxattr
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fastken_fcfs_FCFSFile_getxattr
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_fastken_fcfs_FCFSFile
 * Method:    listxattr
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_fastken_fcfs_FCFSFile_listxattr
  (JNIEnv *, jobject);

/*
 * Class:     com_fastken_fcfs_FCFSFile
 * Method:    chdir
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fastken_fcfs_FCFSFile_chdir
  (JNIEnv *, jobject);

/*
 * Class:     com_fastken_fcfs_FCFSFile
 * Method:    statvfs
 * Signature: ()Lcom/fastken/fcfs/FCFSVFSStat;
 */
JNIEXPORT jobject JNICALL Java_com_fastken_fcfs_FCFSFile_statvfs
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
